### ISSUE TITLE
Chapter 10, sample code runs but follow the steps to create fails.

### ISSUE THREAD

**Issue by wcswanson** [PacktPublishing/Customizing-ASP.NET-Core-6.0#2]
This line of code fails when following the steps in the book but not the sample code:
```
builder.Services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>();
```
Remove ApplicationUser and put IdentityUser in and it runs. ApplicationUser gets the Dependancy Injection error on start up.

`InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.`

The ApplicationDbContext.cs and WebAppUser.cs are exactly the same as the sample code file. Even the csproj files are the same. 
I have tried a different Linux box running Fedora 35 and still get the same error.

**Comment by JuergenGutsch** [comment]
Hi @wcswanson 
Thanks for that hint. I really appreciate that. 
Hope it's not a Linux thing. I'm gonna chack that.
